### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by hugoabonizio** [Fusion/libui.cr#1]
I'm getting this error when running control gallery example.

```
$ crystal src/examples/controlgallery/main.cr 
/home/hugo/.cache/crystal/crystal-run-main.tmp: error while loading shared libraries: libui.so.0: cannot open shared object file: No such file or directory
```

The files libui.so and libui.so.0 are located at /usr/local/lib. What am I doing wrong?

**Comment by Fusion** [comment]
Hugo, this is an issue I am now seeing with all Crystal apps with specific library bindings. I suggest compiling, then running the gallery or whatever application you would write:

Compiling:

    export MYLIBS=/usr/local/lib
    crystal build --link-flags "-L${MYLIBS}" src/examples/controlgallery/main.cr

Running:

    LD_LIBRARY_PATH="$MYLIBS" ./main

Since these are UI applications, on both Linux and OS X a wrapper should be created, that contains this last line. I will hopefully find time to do just that.

**Comment by hugoabonizio** [comment]
This worked here, thanks!

**Comment by hugoabonizio** [comment]
I think this could be on README as this is a recurrent problem for now, what you think?

**Comment by Fusion** [comment]
It is, in the "Development" section. Well, sort of. It refers to the current path because I am assuming that you are packaging the library in the same folder.
I will modify this section to make it more generic.

**Comment by hugoabonizio** [comment]
Oops, my mistake! :smile:
